### ISSUE TITLE
Style the reviews in Review Us section.

### ISSUE THREAD

**Issue by SwanandD121** [subhadeeproy3902/BloxAI#102]
### Is there an existing issue for this?

I have searched the existing issues but haven't found this specific issue.

### What happened?

**Problem**
The reviews which existing customers have given lack some styling. Adding a light border to them would help in separating them from each other which will provide better readability. Also adding subtle hover effects similar to contributor cards will help in maintaining consistency.

**Tasks**
- [ ] Add border to each card.
- [ ] Add hover effects.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SwanandD121** [comment]
Please assign me this under GSSoC'24.

**Comment by subhadeeproy3902** [comment]
there is an already existing issue #87

**Comment by SwanandD121** [comment]
With respect, that issue does not style the review cards, it styles just the review form and adjusts the speed of cards.
Moreover, the implementation should not take more than an hour and it has already been 3 days since the issue you mentioned was raised.

**Comment by AMANKANOJIYA** [comment]
If you want, you can ping us on issue #87 we can help you out there

**Comment by SwanandD121** [comment]
> If you want, you can ping us on issue #87 we can help you out there

Done.
